# Generated by Django 3.0.10 on 2021-11-30 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_followme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userr',
            name='ProfilePic',
            field=models.ImageField(blank=True, upload_to='static/'),
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pheading', models.CharField(max_length=150)),
                ('pimg', models.ImageField(blank=True, upload_to='posts/')),
                ('ptext', models.CharField(max_length=500)),
                ('pdate', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_followme.Userr')),
            ],
        ),
    ]
