# Generated by Django 3.0.10 on 2021-11-30 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_followme', '0002_auto_20211130_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user',
            new_name='userid',
        ),
    ]
